### ISSUE TITLE
TypeError: while completing

### ISSUE THREAD

**Issue by Congee** [myint/clang-complete#1]
I don't know how to title this issue.....

``` C
#include "Python.h"

int main(int argc, char *argv[])
{
    PyObject_Print(PyFloat_FromDouble(E), stdout, 0);
    PyFl  // completion error at here. what I wanna complete is PyFloat_FromDouble.
                 // and it does complete a function name

        // But if I try to complete after the left parenthese, it even doesn't complete the function at all.
        PyObject_Print(PyFl // here
        // So maybe here comes two issues :-(
    return 0;
}
```

The relative code:

``` python
  if base != "":
    # results = [x for x in results
        # if getAbbr(x.string).startswith(base.encode('utf-8'))]
    tmp = []
    for x in results:
      blah = getAbbr(x.string)
      print(blah, type(blah), base, type(base), file=sys.stderr)
      if blah.decode().startswith(base):
        tmp.append(x)
    results = tmp
```

And the :message

```
b'sizeof' <class 'bytes'> PyFl <class 'str'>
Error detected while processing function ClangComplete:
line   22:
b'__PRETTY_FUNCTION__' <class 'bytes'> PyFl <class 'str'>
Error detected while processing function ClangComplete:
line   22:
b'__FUNCTION__' <class 'bytes'> PyFl <class 'str'>
Error detected while processing function ClangComplete:
line   22:
b'__func__' <class 'bytes'> PyFl <class 'str'>
Error detected while processing function ClangComplete:
line   22:
 <class 'str'> PyFl <class 'str'>
Error detected while processing function ClangComplete:
line   22:
Traceback (most recent call last):
Error detected while processing function ClangComplete:
line   22:
  File "<string>", line 1, in <module>
Error detected while processing function ClangComplete:
line   22:
  File "/Users/CC/.vim/bundle/clang-complete/plugin/libclang.py", line 526, in getCurrentCompletions
Error detected while processing function ClangComplete:
line   22:
    if blah.decode().startswith(base):
Error detected while processing function ClangComplete:
line   22:
AttributeError: 'str' object has no attribute 'decode'
Error detected while processing function ClangComplete:
line   23:
Traceback (most recent call last):
Error detected while processing function ClangComplete:
line   23:
  File "<string>", line 1, in <module>
Error detected while processing function ClangComplete:
line   23:
NameError: name 'completions' is not defined
Error detected while processing function ClangComplete:
line   24:
Traceback (most recent call last):
Error detected while processing function ClangComplete:
line   24:
  File "<string>", line 1, in <module>
Error detected while processing function ClangComplete:
line   24:
NameError: name 'timer' is not defined
Error detected while processing function ClangComplete:
-- More --
```

Note that all the getAbbr(x.string) is `<class 'bytes'>` except the last element `' '` (a space char) which is `<class 'str'>`
I'm not familiar with clang-complete and didn't step into the repo.
May this message helpful.

**Comment by Congee** [comment]
`results` doesn't support `slice()` and I came up with a workaround: add `if isinstance(blah, str): break`.
Ugly workaround....

**Comment by congee** [comment]
`results` doesn't support `slice()` and I came up with a workaround: add `if isinstance(blah, str): break`.
Ugly workaround....

**Comment by myint** [comment]
I can't reproduce the error when trying out your example. But in any case, try with the [latest](https://github.com/myint/clang-complete/commit/86c5dd32ab2749941463eeaa3fa1274285a16ace) in the master branch. Please let me know if it fixes the error.

**Comment by Congee** [comment]
@myint Your patch works greatly. Thanks :-)
